#                                        Sign Language Detection Using Deep Learning 

### Setting Work Envirement

In [8]:
import cv2 
import numpy as np 
import os 
from matplotlib import pyplot as plt
import time
import mediapipe as mp 

In [9]:
mp_holistic=mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils

### Mediapipe Application

In [10]:
def mediapipe_detection(frame,model):
    # Convert the frame from BGR to RGB and flip it horizontally
    frame = cv2.cvtColor(cv2.flip(frame, 1), cv2.COLOR_BGR2RGB)
    frame.flags.writeable = False
    # Process the frame using the detection model
    results=model.process(frame)
    # Set the frame to be writable again
    frame.flags.writeable = True
    # Convert the frame back to BGR format
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    return frame,results

In [11]:
def draw_landmarks(frame, results):
    mp_drawing.draw_landmarks(
        frame,
        results.face_landmarks,
        mp_holistic.FACEMESH_TESSELATION,
        mp_drawing.DrawingSpec(color=(80, 110, 10), thickness=1, circle_radius=1),
        mp_drawing.DrawingSpec(color=(80, 256, 121), thickness=1, circle_radius=1),
    )
    mp_drawing.draw_landmarks(
        frame, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS
    )
    mp_drawing.draw_landmarks(
        frame, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS
    )
    mp_drawing.draw_landmarks(
        frame, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS
    )


In [12]:
def draw_styled_landmarks(frame, results):
    mp_drawing.draw_landmarks(
        frame,
        results.face_landmarks,
        mp_holistic.FACEMESH_TESSELATION,
        mp_drawing.DrawingSpec(color=(80, 110, 10), thickness=1, circle_radius=1),
    )
    mp_drawing.draw_landmarks(
        frame, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS
    )
    mp_drawing.draw_landmarks(
        frame, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS
    )
    mp_drawing.draw_landmarks(
        frame, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS
    )


In [13]:
#Getting Camera Feed 
cap =cv2.VideoCapture(0)
#Setting Mediapipe model
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    while cap.isOpened() :
        ret,frame=cap.read()
        frame , results = mediapipe_detection(frame,holistic)
        draw_landmarks(frame,results)
        
        cv2.imshow('Camera Feed ',frame)
        if cv2.waitKey(10) & 0xFF == ord('q') :
            break
cap.release()
cv2.destroyAllWindows()

### Extracting Meadiapipe Detection Results

In [14]:
#Extracting Pose Landmarks
Pose_Landmarks_list=[]
for res in results.pose_landmarks.landmark:
    test=np.array([res.x,res.y,res.z,res.visibility])
    Pose_Landmarks_list.append(test)

In [15]:
Pose_Landmarks_list

[array([ 0.31086108,  0.5547837 , -0.57461476,  0.99978483]),
 array([ 0.34450692,  0.48787406, -0.60163045,  0.99953556]),
 array([ 0.3620517 ,  0.48541498, -0.60130334,  0.99963987]),
 array([ 0.38180122,  0.48392895, -0.60156685,  0.99957287]),
 array([ 0.31258565,  0.48897165, -0.53131455,  0.99952334]),
 array([ 0.30412278,  0.48765218, -0.53048682,  0.9996016 ]),
 array([ 0.29748589,  0.48580307, -0.53083622,  0.99954307]),
 array([ 0.44406325,  0.49934348, -0.53570676,  0.99961668]),
 array([ 0.32171077,  0.49582428, -0.18484254,  0.99961567]),
 array([ 0.34754926,  0.61533105, -0.53687155,  0.9997344 ]),
 array([ 0.30736089,  0.61636132, -0.43640423,  0.99970269]),
 array([ 0.66114247,  0.8456279 , -0.41492993,  0.99739468]),
 array([ 0.21403284,  0.85792404, -0.10723577,  0.99917775]),
 array([ 0.76047903,  1.25563967, -0.40630084,  0.08702706]),
 array([0.13642487, 1.25054598, 0.02284505, 0.12494288]),
 array([ 0.74574429,  1.56223667, -0.45543075,  0.02159543]),
 array([ 0.1

In [16]:
Pose_Landmarks_list=np.array([[res.x,res.y,res.z,res.visibility] for result in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)

In [17]:
Pose_Landmarks_list

array([ 3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  3.03393555e+00, -1.06586598e-01,  3.37585079e-05,
        3.63914490e-01,  

In [18]:
left_hand_landmarks_list=np.array([[res.x,res.y,res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21 * 3)

In [19]:
right_hand_landmarks_list=np.array([[res.x,res.y,res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [20]:
right_hand_landmarks_list

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
face_landmarks_list=np.array([[res.x,res.y,res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)

In [22]:
face_landmarks_list

array([ 0.28253055,  0.61635333, -0.01433329, ...,  0.36227047,
        0.4780277 , -0.04873035])

In [80]:
def extract_landmarks(results):
    pose_landmarks_list = (
        np.array(
            [
                [landmark.x, landmark.y, landmark.z, landmark.visibility]
                for landmark in results.pose_landmarks.landmark
            ]
        ).flatten()
        if results.pose_landmarks
        else np.zeros(132)
    )
    left_hand_landmarks_list = (
        np.array(
            [[landmark.x, landmark.y, landmark.z] for landmark in results.left_hand_landmarks.landmark]
        ).flatten()
        if results.left_hand_landmarks
        else np.zeros(21 * 3)
    )
    right_hand_landmarks_list = (
        np.array(
            [[landmark.x, landmark.y, landmark.z] for landmark in results.right_hand_landmarks.landmark]
        ).flatten()
        if results.right_hand_landmarks
        else np.zeros(21 * 3)
    )

    return np.concatenate((pose_landmarks_list, left_hand_landmarks_list, right_hand_landmarks_list))


In [81]:
extract_landmarks(results).shape

(258,)

### Data Collection

##### Setting Folders 

In [25]:
#Path for the collected data
DATA_PATH=os.path.join('MP_DATA')
#Actions to detect
actions=np.array(['hello','thanks','iloveyou'])
#Number of videos
no_sequences=30
#Length of each video 
sequence_length=30

In [26]:
for action in actions :
    for seq in range(no_sequences) :
        try :
            os.makedirs(os.path.join(DATA_PATH,action,str(seq)))
        except :
            pass

In [27]:
#Getting Camera Feed 
cap =cv2.VideoCapture(0)
#Setting Mediapipe model
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    #Loop throught actions
    for action in actions :
        #Loop throught sequences 
        for seq in range(no_sequences) :
            #Loop throught video length
            for frame_nbr in range(sequence_length):
                
                ret,frame=cap.read()
                frame , results = mediapipe_detection(frame,holistic)
                draw_landmarks(frame,results)
                if frame_nbr == 0:
                    
                    cv2.putText(frame, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(frame, 'Collecting frames for {} Video Number {}'.format(action, seq), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    cv2.imshow('OpenCV Feed', frame)
                    #cv2.imshow('Camera Feed ',frame)
                    cv2.waitKey(2000)
                else :
                    cv2.putText(frame, 'Collecting frames for {} Video Number {}'.format(action, seq), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', frame)  
                
                # NEW Export keypoints
                keypoints = extract_landmarks(results)
                npy_path = os.path.join(DATA_PATH, action, str(seq), str(frame_nbr))
                np.save(npy_path, keypoints)
                
                if cv2.waitKey(10) & 0xFF == ord('q') :
                    break
cap.release()
cv2.destroyAllWindows()

### Data Preprocessing 

In [28]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical 

In [30]:
#creatin a label map 
label_map = {label:num for num , label in enumerate(actions)}


In [31]:
label_map

{'hello': 0, 'thanks': 1, 'iloveyou': 2}

In [34]:
sequences ,labels=[],[]
for action in actions :
    for sequence in range(no_sequences):
        window=[]
        for frame_num in range(sequence_length):
            res=np.load(os.path.join(DATA_PATH,action,str(sequence),"{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [37]:
np.array(sequences).shape

(90, 30, 258)

In [38]:
np.array(labels).shape

(90,)

In [39]:
X=np.array(sequences)


In [40]:
X.shape

(90, 30, 258)

In [41]:
y=to_categorical(labels).astype(int)

In [43]:
y.shape

(90, 3)

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.05)

In [48]:
X_test.shape

(5, 30, 258)

In [49]:
y_test.shape

(5, 3)

### LSTM Neural Network 

In [50]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import LSTM , Dense
from tensorflow.keras.callbacks import TensorBoard

In [53]:
#Setting Logs Directory and Tensorboard
log_dir=os.path.join('Logs')
tb_callback=TensorBoard(log_dir = log_dir)

In [57]:
#Neural Network Architecture 
model = Sequential()
model.add(LSTM(64,return_sequences=True,activation='relu',input_shape=(30,258)))
model.add(LSTM(128,return_sequences=True,activation='relu'))
model.add(LSTM(64,return_sequences=False,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(actions.shape[0],activation='softmax'))

In [60]:
res=[0.5,0.3,0.2]
np.argmax(res)
actions[np.argmax(res)]

'hello'

In [61]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])

In [63]:
model.fit(X_train,y_train,epochs=2000,callbacks=[tb_callback])

Epoch 1/2000
3/3 [==============================] - 0s 36ms/step - loss: 0.2064 - categorical_accuracy: 0.9294
Epoch 2/2000
3/3 [==============================] - 0s 35ms/step - loss: 0.1786 - categorical_accuracy: 0.9647
Epoch 3/2000
3/3 [==============================] - 0s 34ms/step - loss: 0.1459 - categorical_accuracy: 0.9647
Epoch 4/2000
3/3 [==============================] - 0s 35ms/step - loss: 0.1579 - categorical_accuracy: 0.9176
Epoch 5/2000
3/3 [==============================] - 0s 37ms/step - loss: 0.1195 - categorical_accuracy: 0.9529
Epoch 6/2000
3/3 [==============================] - 0s 35ms/step - loss: 0.1279 - categorical_accuracy: 0.9294
Epoch 7/2000
3/3 [==============================] - 0s 35ms/step - loss: 0.1101 - categorical_accuracy: 0.9647
Epoch 8/2000
3/3 [==============================] - 0s 35ms/step - loss: 0.0887 - categorical_accuracy: 0.9765
Epoch 9/2000
3/3 [==============================] - 0s 35ms/step - loss: 0.1052 - categorical_accuracy: 0.9529
E

KeyboardInterrupt: 

In [64]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 30, 64)            82688     
                                                                 
 lstm_4 (LSTM)               (None, 30, 128)           98816     
                                                                 
 lstm_5 (LSTM)               (None, 64)                49408     
                                                                 
 dense_3 (Dense)             (None, 64)                4160      
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 237251 (926.76 KB)
Trainable params: 237

In [66]:
res=model.predict(X_test)

1/1 [==============================] - 0s 31ms/step


In [68]:
np.argmax(res[0])

0

In [69]:
actions[np.argmax(res[0])]

'hello'

In [70]:
actions[np.argmax(y_test[0])]

'iloveyou'

In [71]:
model.save('action.h5')

D:\miniconda\envs\ml\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### Model Evaluation

In [72]:
from sklearn.metrics import multilabel_confusion_matrix ,accuracy_score 


In [73]:
yhat=model.predict(X_test)
y_true=np.argmax(y_test,axis=1).tolist()
yhat=np.argmax(yhat,axis=1).tolist()

1/1 [==============================] - 0s 32ms/step


In [74]:
multilabel_confusion_matrix(y_true,yhat)

array([[[2, 1],
        [0, 2]],

       [[2, 0],
        [1, 2]]], dtype=int64)

In [75]:
accuracy_score(y_true,yhat)

0.8

In [83]:
colors = [(245,117,16), (117,245,16), (16,117,245)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [85]:
# 1. New detection variables
sequence = []
sentence = []
threshold = 0.8

cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_landmarks(results)
#         sequence.insert(0,keypoints)
#         sequence = sequence[:30]
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            
            
        #3. Viz logic
            if res[np.argmax(res)] > threshold: 
                if len(sentence) > 0: 
                    if actions[np.argmax(res)] != sentence[-1]:
                        sentence.append(actions[np.argmax(res)])
                else:
                    sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

KeyboardInterrupt: 